# Generated by Django 3.1.2 on 2020-10-08 05:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='callsign',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='imei',
            field=models.CharField(default='', max_length=16, validators=[django.core.validators.MinLengthValidator(15)]),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('balloon', 'Balloon'), ('buoy', 'Buoy')], default='balloon', max_length=32),
        ),
    ]
